-- FILTRAR PRIMEIRA LINHA
SELECT * FROM TB_TAB WHERE ROWNUM =1

-- ALTERAR FORMATO DE COLUNAS
ALTER TABLE TB_TAB
MODIFY (GRUPO CHAR(50))

-- CRIAR TABELA TEMPORARIA NO PL/SQL
WITH
TB_PVS AS (SELECT * FROM TB_TAB),
TB_PVS2 AS (SELECT * FROM TB_TAB)

SELECT * FROM TB_PVS2;

-- CORTANDO ESPACOES EM BRANCO DE TABELAS
SELECT TRIM(PERFIL_MBS) AS PERFIL_MBS FROM TABELA;

-- JOINS (COLOCAR ANTES DO WHERE)
LEFT JOIN TB_TAB2 TB2
ON TB1.COLUNA = TB2.COLUNA
-- JOINS DUPLOS PODEM ENTRAR ABAIXO UM DO OUTRO
LEFT JOIN TB_TAB2 TB2
ON TB1.COLUNA = TB2.COLUNA

-- COMO CRIAR PROCEDURES

-- FORMA 1: CRIANDO PROCEDURE UNICA E PASSANDO VARIAVEIS COM DECLARE EM CONSULTA SEPARADA
CREATE OR REPLACE PROCEDURE SCHEMA.PROCEDURE_TB_TAB (NPARTITION VARCHAR2) AS
NPARTITION2 VARCHAR2(8)
BEGIN
NPARTITION2 := NPARTITION;

EXECUTE IMMEDIATE '
SELECT * FROM TB_TAB PARTITION ('||NPARTITION2||')';
COMMIT;

END;

-- PASSANDO VARIAVEIS E A EXECUCAO DA FORMA 1
DECLARE
PARTITION1TRI VARCHAR(8);
PARTITION2TRI VARCHAR(8);
BEGIN
-- CAPTURA A PARTITION MAIS RECENTE DO 1 TRIMESTRE
	SELECT MAX(COLUNA) INTO PARTITION1TRI
	FROM (SELECT DSPARTITION FROM TB_TAB WHERE ROWNUM = 1);
-- CAPTURA A PARTITION MAIS RECENTE DO 2 TRIMESTRE
	SELECT MAX(COLUNA) INTO PARTITION1TRI
	FROM (SELECT DSPARTITION FROM TB_TAB WHERE ROWNUM = 2);
-- PRINTA NO OUTPUT OS VALORES DAS VARIAVEIS
	dbms_output.put_line(partition1tri);
	dbms_output.put_line(partition2tri);


SCHEMA.PROCEDURE_TB_TAB (PARTITION1TRI);
SCHEMA.PROCEDURE_TB_TAB (PARTITION2TRI);
END;


--FORMA 2: COLOCAR O CODIGO INTEIRO DENTRO DO JOB

-----------------------------------------------

--- JOB NO ORACLE
BEGIN
SYS.DBMS_SCHEDULER.CREATE_JOB
(
  JOB_NAME => 'SCHEMA.TB_TAB' -- QUALQUER NOME
, START_DATE => '14/10/22 12:55:00,250000 -03:00' -- DATA DE INICIO (COLOCAR DATA QUE AINDA NAO ACONTECEU)
, REPEAT_INTERVAL => 'FREQ= DAILY; INTERVAL=1'
, END_DATE => '12/09/26 12:55:00,250000 -03:00' -- DATA DE TERMINO
, JOB_TYPE => 'PLSQL_BLOCK' -- MANTER PARA COLOCAR CONSULTA NO JOB ACTION
, JOB_ACTION => 'SELECT * FROM TB_TAB' -- COLOCAR CONSULTA AQUI
, ENABLED => TRUE) -- ATIVAR OU DESATIVAR JOB;
END;